remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme
title: Code Snippet Plugin - BF2042 Portal Rules Editor
description: This is a plugin for the Battlefield Portal Browser Extension to provide code snippets to insert into the workspace of the Battlefield 2042 Portal Rules Editor.
